# Generated by Django 6.0.6 on 2026-07-09 08:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0001_initial'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='contribution_period',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contribution',
            name='reference',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddConstraint(
            model_name='contribution',
            constraint=models.UniqueConstraint(fields=('member', 'contribution_period'), name='unique_member_contribution_period'),
        ),
    ]
