# Generated by Django 6.0.6 on 2026-07-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0002_contribution_contribution_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='currency',
            field=models.CharField(default='MZN', max_length=3),
        ),
    ]
