# Generated by Django 6.0.6 on 2026-08-22 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0003_contribution_currency'),
        ('groups', '0003_alter_groupsettings_options_groupsettings_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='group_settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contributions', to='groups.groupsettings'),
        ),
    ]
