# Generated by Django 6.0.6 on 2026-08-22 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0004_contribution_group_settings'),
        ('groups', '0003_alter_groupsettings_options_groupsettings_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='group_settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contributions', to='groups.groupsettings'),
        ),
    ]
