# Generated by Django 6.0.6 on 2026-07-12 10:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDID',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(choices=[('KEY', 'did:key')], default='KEY', max_length=20)),
                ('did', models.CharField(editable=False, max_length=255, unique=True)),
                ('public_key_multibase', models.CharField(editable=False, max_length=255, unique=True)),
                ('encrypted_private_key', models.TextField(editable=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('REVOKED', 'Revoked')], default='ACTIVE', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='decentralized_identity', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_dids',
            },
        ),
    ]
