# Generated by Django 6.0.6 on 2026-07-12 10:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupDID',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(choices=[('KEY', 'did:key')], default='KEY', max_length=20)),
                ('did', models.CharField(editable=False, max_length=255, unique=True)),
                ('public_key_multibase', models.CharField(editable=False, max_length=255, unique=True)),
                ('encrypted_private_key', models.TextField(editable=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('REVOKED', 'Revoked')], default='ACTIVE', max_length=20)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='decentralized_identity', to='groups.group')),
            ],
            options={
                'db_table': 'group_dids',
            },
        ),
    ]
