# Generated by Django 6.0.6 on 2026-07-27 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('credentials', '0004_remove_blockchainanchor_credentials_credent_c56008_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockchainAnchor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(max_length=50)),
                ('contract_address', models.CharField(max_length=42)),
                ('transaction_hash', models.CharField(max_length=66, unique=True)),
                ('block_number', models.BigIntegerField()),
                ('wallet_address', models.CharField(max_length=42)),
                ('anchored_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('FAILED', 'Failed'), ('REPLACED', 'Replaced')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anchors', to='credentials.verifiablecredential')),
            ],
            options={
                'indexes': [models.Index(fields=['credential'], name='blockchain__credent_fd6d26_idx'), models.Index(fields=['transaction_hash'], name='blockchain__transac_718b74_idx'), models.Index(fields=['status'], name='blockchain__status_b1960c_idx')],
            },
        ),
    ]
