# Generated by Django 6.0.6 on 2026-08-23 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0001_initial'),
        ('contributions', '0005_alter_contribution_group_settings'),
        ('credentials', '0004_remove_blockchainanchor_credentials_credent_c56008_idx_and_more'),
        ('groups', '0003_alter_groupsettings_options_groupsettings_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockchainanchor',
            name='anchor_type',
            field=models.CharField(choices=[('CREDENTIAL', 'Credential'), ('GROUP_SETTINGS', 'Group Settings'), ('CONTRIBUTION', 'Contribution'), ('DISBURSEMENT', 'Disbursement')], default='CREDENTIAL', max_length=30),
        ),
        migrations.AddField(
            model_name='blockchainanchor',
            name='content_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='blockchainanchor',
            name='contribution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='anchors', to='contributions.contribution'),
        ),
        migrations.AddField(
            model_name='blockchainanchor',
            name='group_settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='anchors', to='groups.groupsettings'),
        ),
        migrations.AlterField(
            model_name='blockchainanchor',
            name='credential',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='anchors', to='credentials.verifiablecredential'),
        ),
        migrations.AddIndex(
            model_name='blockchainanchor',
            index=models.Index(fields=['anchor_type'], name='blockchain__anchor__f4e51d_idx'),
        ),
        migrations.AddIndex(
            model_name='blockchainanchor',
            index=models.Index(fields=['content_hash'], name='blockchain__content_c127b5_idx'),
        ),
        migrations.AddIndex(
            model_name='blockchainanchor',
            index=models.Index(fields=['group_settings'], name='blockchain__group_s_94e1dd_idx'),
        ),
        migrations.AddIndex(
            model_name='blockchainanchor',
            index=models.Index(fields=['contribution'], name='blockchain__contrib_d50eff_idx'),
        ),
    ]
