# Generated by Django 6.0.6 on 2026-08-23 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0002_blockchainanchor_anchor_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockchainanchor',
            name='anchor_type',
            field=models.CharField(choices=[('CREDENTIAL', 'Credential'), ('GROUP_SETTINGS', 'Group Settings'), ('CONTRIBUTION', 'Contribution'), ('DISBURSEMENT', 'Disbursement')], max_length=30),
        ),
        migrations.AlterField(
            model_name='blockchainanchor',
            name='content_hash',
            field=models.CharField(max_length=64),
        ),
    ]
