# Generated by Django 6.0.6 on 2026-07-12 11:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0002_groupsettings_currency'),
        ('identity', '0002_groupdid'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifiableCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credential_type', models.CharField(choices=[('CONTRIBUTION_HISTORY', 'Contribution History')], default='CONTRIBUTION_HISTORY', max_length=40)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('credential_document', models.JSONField()),
                ('credential_hash', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('REVOKED', 'Revoked')], default='ACTIVE', max_length=20)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_reason', models.TextField(blank=True)),
                ('group_member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verifiable_credentials', to='groups.groupmember')),
                ('holder_did', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credentials', to='identity.userdid')),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_credentials', to='groups.groupmember')),
                ('issuer_did', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_credentials', to='identity.groupdid')),
            ],
            options={
                'db_table': 'verifiable_credentials',
                'ordering': ['-valid_from'],
                'indexes': [models.Index(fields=['group_member', 'credential_type', 'status'], name='vc_member_type_status_idx'), models.Index(fields=['credential_hash'], name='vc_hash_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('period_end__gte', models.F('period_start'))), name='vc_period_end_after_start'), models.CheckConstraint(condition=models.Q(('valid_until__isnull', True), ('valid_until__gt', models.F('valid_from')), _connector='OR'), name='vc_valid_until_after_valid_from')],
            },
        ),
    ]
