# Generated by Django 6.0.6 on 2026-07-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0001_initial'),
        ('groups', '0002_groupsettings_currency'),
        ('identity', '0002_groupdid'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='verifiablecredential',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('group_member', 'credential_type', 'period_start', 'period_end'), name='unique_active_vc_member_period'),
        ),
    ]
