# Generated by Django 6.0.6 on 2026-07-21 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0002_verifiablecredential_unique_active_vc_member_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockchainAnchor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential_hash', models.BinaryField(max_length=32)),
                ('network', models.CharField(max_length=30)),
                ('contract_address', models.CharField(max_length=42)),
                ('transaction_hash', models.CharField(max_length=66, unique=True)),
                ('block_hash', models.CharField(max_length=66)),
                ('block_number', models.PositiveBigIntegerField()),
                ('wallet_address', models.CharField(max_length=42)),
                ('gas_used', models.PositiveBigIntegerField()),
                ('effective_gas_price', models.PositiveBigIntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('FAILED', 'Failed')], default='CONFIRMED', max_length=20)),
                ('anchored_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anchors', to='credentials.verifiablecredential')),
            ],
            options={
                'ordering': ['-anchored_at'],
                'indexes': [models.Index(fields=['credential'], name='credentials_credent_c56008_idx'), models.Index(fields=['credential_hash'], name='credentials_credent_cb4fd5_idx'), models.Index(fields=['transaction_hash'], name='credentials_transac_b64e65_idx'), models.Index(fields=['status'], name='credentials_status_2da61c_idx')],
            },
        ),
    ]
