# Generated by Django 6.0.6 on 2026-07-27 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0003_blockchainanchor'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='blockchainanchor',
            name='credentials_credent_c56008_idx',
        ),
        migrations.RemoveIndex(
            model_name='blockchainanchor',
            name='credentials_credent_cb4fd5_idx',
        ),
        migrations.RemoveIndex(
            model_name='blockchainanchor',
            name='credentials_transac_b64e65_idx',
        ),
        migrations.RemoveIndex(
            model_name='blockchainanchor',
            name='credentials_status_2da61c_idx',
        ),
        migrations.DeleteModel(
            name='BlockchainAnchor',
        ),
    ]
