# Generated by Django 6.0.6 on 2026-07-07 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='rrole',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('GESTOR', 'Gestor'), ('TESOUREIRO', 'Tesoureiro'), ('MEMBRO', 'Membro')], default='MEMBRO', max_length=20),
        ),
    ]
