# Generated by Django 6.0.6 on 2026-07-07 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_role_user_rrole'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='rrole',
            new_name='role',
        ),
    ]
