# Generated by Django 6.0.6 on 2026-08-23 14:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0006_rotationorder_unique_current_rotation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disbursement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cycle_number', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('AWAITING_CONSENSUS', 'Awaiting consensus'), ('APPROVED', 'Approved'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=30)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disbursements', to='groups.groupmember')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disbursements', to='groups.group')),
                ('group_settings', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disbursements', to='groups.groupsettings')),
                ('rotation_order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='disbursement', to='groups.rotationorder')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['group', 'cycle_number'], name='disb_group_cycle_idx'), models.Index(fields=['status'], name='disb_status_idx')],
            },
        ),
    ]
