# Generated by Django 6.0.6 on 2026-07-12 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupsettings',
            name='currency',
            field=models.CharField(default='MZN', max_length=3),
        ),
    ]
