# Generated by Django 6.0.6 on 2026-08-22 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_groupsettings_currency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupsettings',
            options={'ordering': ['group', '-version']},
        ),
        migrations.AddField(
            model_name='groupsettings',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='groupsettings',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='groupsettings',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings_versions', to='groups.group'),
        ),
        migrations.AddConstraint(
            model_name='groupsettings',
            constraint=models.UniqueConstraint(fields=('group', 'version'), name='unique_group_settings_version'),
        ),
        migrations.AddConstraint(
            model_name='groupsettings',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('group',), name='unique_active_group_settings'),
        ),
    ]
