# Generated by Django 6.0.6 on 2026-08-23 09:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_alter_groupsettings_options_groupsettings_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RotationOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cycle_number', models.PositiveIntegerField()),
                ('position', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CURRENT', 'Current'), ('COMPLETED', 'Completed'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=20)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rotation_orders', to='groups.group')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rotation_orders', to='groups.groupmember')),
            ],
            options={
                'db_table': 'rotation_orders',
                'ordering': ['cycle_number', 'position'],
                'indexes': [models.Index(fields=['group', 'cycle_number', 'status'], name='rotation_group_cycle_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('group', 'cycle_number', 'position'), name='unique_rotation_position_per_cycle'), models.UniqueConstraint(fields=('group', 'cycle_number', 'member'), name='unique_member_per_rotation_cycle')],
            },
        ),
    ]
