# Generated by Django 6.0.6 on 2026-08-23 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_rotationorder'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='rotationorder',
            new_name='rot_grp_cycle_stat_idx',
            old_name='rotation_group_cycle_status_idx',
        ),
    ]
