# Generated by Django 6.0.6 on 2026-08-23 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_rename_rotation_group_cycle_status_idx_rot_grp_cycle_stat_idx'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='rotationorder',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'CURRENT')), fields=('group', 'cycle_number'), name='unique_current_rotation'),
        ),
    ]
