# Generated by Django 6.0.6 on 2026-08-23 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_rotationorder_unique_current_rotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='rotationorder',
            name='contribution_period',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rotationorder',
            name='group_settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rotation_orders', to='groups.groupsettings'),
        ),
    ]
