# Generated by Django 6.0.6 on 2026-08-23 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0007_rotationorder_contribution_period_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rotationorder',
            name='contribution_period',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='rotationorder',
            name='group_settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rotation_orders', to='groups.groupsettings'),
        ),
    ]
